#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0
rm -f *.err
rm -f *.out
rm -f core.[0-9]*
rm -f setSet_logs
rm -f refineMesh_logs

#------------------------------------------------------------------------------
