#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

restore0Dir


runApplication blockMesh

#runApplication setSet -batch top6.setSet 
#rm -f log.setSet 
 runApplication decomposePar 
# runParallel setSet -batch top6.setSet 
# cat log.setSet >> setSet_logs
# echo "---------------" >> setSet_logs
# rm -f log.setSet 

# initialize all sets
source ./runSet 
rm -f log.setSet 

for i in {1..5}
do
source ./runRefine "xp1"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "xm1"
source ./runSet 
rm -f log.setSet log.refineMesh
done

echo "-------1-------"

for i in {1..4}
do
source ./runRefine "xp2"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "xm2"
source ./runSet 
rm -f log.setSet log.refineMesh
done

echo "-------2-------"

for i in {1..3}
do
source ./runRefine "xp3"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "xm3"
source ./runSet 
rm -f log.setSet log.refineMesh
done

echo "-------3-------"

for i in {1..2}
do
source ./runRefine "xp4"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "xm4"
source ./runSet 
rm -f log.setSet log.refineMesh
done

echo "-------4-------"

for i in {1..2}
do
source ./runRefine "yp1"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "ym1"
source ./runSet 
rm -f log.setSet log.refineMesh
done

echo "-------y1-------"

source ./runRefine "yp2"
source ./runSet 
rm -f log.setSet log.refineMesh
source ./runRefine "ym2"
source ./runSet 

echo "-------y2-------"

runParallel setFields
runParallel $(getApplication)



