#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cp -r 0.orig 0 > /dev/null 2>&1
# runApplication blockMesh
# runApplication setSet -batch top6.setSet
# runApplication setFields

# runApplication decomposePar
runParallel $(getApplication)
# runApplication reconstructParMesh -constant
# runApplication reconstructPar

# runApplication $(getApplication)
#------------------------------------------------------------------------------
